# Generated by Django 5.2.12 on 2026-03-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('total_count', models.IntegerField(default=0)),
                ('positive_count', models.IntegerField(default=0)),
                ('neutral_count', models.IntegerField(default=0)),
                ('negative_count', models.IntegerField(default=0)),
                ('avg_sentiment_score', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'category_sentiment',
            },
        ),
        migrations.CreateModel(
            name='DateSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_str', models.CharField(max_length=20)),
                ('total_count', models.IntegerField(default=0)),
                ('positive_count', models.IntegerField(default=0)),
                ('neutral_count', models.IntegerField(default=0)),
                ('negative_count', models.IntegerField(default=0)),
                ('avg_sentiment_score', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'date_sentiment',
            },
        ),
        migrations.CreateModel(
            name='OverallSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_news', models.IntegerField(default=0)),
                ('positive_count', models.IntegerField(default=0)),
                ('neutral_count', models.IntegerField(default=0)),
                ('negative_count', models.IntegerField(default=0)),
                ('positive_pct', models.FloatField(default=0.0)),
                ('neutral_pct', models.FloatField(default=0.0)),
                ('negative_pct', models.FloatField(default=0.0)),
                ('avg_sentiment_score', models.FloatField(default=0.0)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'overall_sentiment',
            },
        ),
        migrations.CreateModel(
            name='ScoreDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_range', models.CharField(max_length=30)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'score_distribution',
            },
        ),
        migrations.CreateModel(
            name='SentimentKeywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50)),
                ('frequency', models.IntegerField(default=0)),
                ('sentiment', models.CharField(default='all', max_length=20)),
            ],
            options={
                'db_table': 'sentiment_keywords',
            },
        ),
        migrations.CreateModel(
            name='SourceSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('total_count', models.IntegerField(default=0)),
                ('positive_count', models.IntegerField(default=0)),
                ('neutral_count', models.IntegerField(default=0)),
                ('negative_count', models.IntegerField(default=0)),
                ('avg_sentiment_score', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'source_sentiment',
            },
        ),
        migrations.CreateModel(
            name='NewsSentimentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_clean', models.CharField(blank=True, max_length=255, null=True, verbose_name='清洗后标题')),
                ('content_clean', models.TextField(blank=True, null=True, verbose_name='清洗后内容')),
                ('title_standard', models.CharField(blank=True, max_length=255, null=True, verbose_name='标准化标题')),
                ('content_standard', models.TextField(blank=True, null=True, verbose_name='标准化内容')),
                ('source', models.CharField(blank=True, max_length=100, null=True, verbose_name='来源')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='分类')),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('url', models.CharField(max_length=500, unique=True, verbose_name='链接')),
                ('read_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='阅读量')),
                ('comment_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='评论数')),
                ('like_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='点赞数')),
                ('title_len', models.IntegerField(blank=True, default=0, null=True, verbose_name='标题长度')),
                ('content_len', models.IntegerField(blank=True, default=0, null=True, verbose_name='内容长度')),
                ('content_token_len', models.IntegerField(blank=True, default=0, null=True, verbose_name='内容Token数')),
                ('sentiment', models.CharField(blank=True, max_length=20, null=True, verbose_name='情感')),
                ('sentiment_score', models.FloatField(blank=True, null=True, verbose_name='情感得分')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '新闻情感分析',
                'verbose_name_plural': '新闻情感分析',
                'db_table': 'app_newssentimentanalysis',
                'indexes': [models.Index(fields=['url'], name='app_newssen_url_d352dc_idx'), models.Index(fields=['source'], name='app_newssen_source_6cd6a2_idx'), models.Index(fields=['publish_date'], name='app_newssen_publish_ccd8ab_idx'), models.Index(fields=['category'], name='app_newssen_categor_ebe17d_idx')],
                'unique_together': {('url',)},
            },
        ),
    ]
