# Generated by Django 5.2.12 on 2026-03-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newssentimentanalysis',
            name='url',
            field=models.CharField(max_length=255, unique=True, verbose_name='链接'),
        ),
    ]
