# Generated by Django 5.2.12 on 2026-03-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_newssentimentanalysis_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='原始标题')),
                ('content', models.TextField(blank=True, null=True, verbose_name='原始内容')),
                ('source', models.CharField(blank=True, max_length=100, null=True, verbose_name='来源')),
                ('url', models.CharField(max_length=255, unique=True, verbose_name='链接')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='分类')),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('read_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='阅读量')),
                ('comment_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='评论数')),
                ('like_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='点赞数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '新闻原始数据',
                'verbose_name_plural': '新闻原始数据',
                'db_table': 'app_newsraw',
                'indexes': [models.Index(fields=['url'], name='app_newsraw_url_1234d7_idx'), models.Index(fields=['source'], name='app_newsraw_source_7f36e6_idx'), models.Index(fields=['publish_date'], name='app_newsraw_publish_50dc35_idx'), models.Index(fields=['category'], name='app_newsraw_categor_67f6e0_idx')],
                'unique_together': {('url',)},
            },
        ),
    ]
