# Generated by Django 5.2.12 on 2026-05-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_newsraw'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='newsraw',
            index=models.Index(fields=['create_time'], name='app_newsraw_create__a954dd_idx'),
        ),
        migrations.AddIndex(
            model_name='newssentimentanalysis',
            index=models.Index(fields=['sentiment'], name='app_newssen_sentime_d15afc_idx'),
        ),
        migrations.AddIndex(
            model_name='newssentimentanalysis',
            index=models.Index(fields=['create_time'], name='app_newssen_create__8ebd9a_idx'),
        ),
    ]
